version: '3.8'

services: 
  mysql:
    build: ./mysql
    tty: true
    ports: 
        - "3306:3306"
    container_name: mysql
    environment: 
        MYSQL_USER: admin
        MYSQL_ROOT_PASSWORD: P@ssW0rd
        MYSQL_PASSWORD: P@ssW0rd
        MYSQL_DATABASE: traning
    platform: linux/x86_64
    networks: 
      - backend

  python:
    build: ./python
    tty: true
    ports: 
      - "8080:8080"
    container_name: python
    volumes: 
      - ./python:/usr/src
    depends_on:
      - mysql
    networks: 
      - backend
      - frontend

  react:
    build: ./react
    tty: true
    ports:
      - "3000:3000"
    container_name: react
    volumes: 
        - ./react/app:/usr/src/app
        - /usr/src/app/node_modules
    depends_on:
      - python
    networks:
      - frontend

networks:
  backend:
  frontend:



  